// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.7.1
// source: micro.proto

package micro

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HttpAuthenticationType int32

const (
	HttpAuthenticationType_MICRO_HTTP_AUTHENTICATION_TYPE_UNSPECIFIED HttpAuthenticationType = 0
	HttpAuthenticationType_MICRO_HTTP_AUTHENTICATION_TYPE_BEARER      HttpAuthenticationType = 1
)

// Enum value maps for HttpAuthenticationType.
var (
	HttpAuthenticationType_name = map[int32]string{
		0: "MICRO_HTTP_AUTHENTICATION_TYPE_UNSPECIFIED",
		1: "MICRO_HTTP_AUTHENTICATION_TYPE_BEARER",
	}
	HttpAuthenticationType_value = map[string]int32{
		"MICRO_HTTP_AUTHENTICATION_TYPE_UNSPECIFIED": 0,
		"MICRO_HTTP_AUTHENTICATION_TYPE_BEARER":      1,
	}
)

func (x HttpAuthenticationType) Enum() *HttpAuthenticationType {
	p := new(HttpAuthenticationType)
	*p = x
	return p
}

func (x HttpAuthenticationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HttpAuthenticationType) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_proto_enumTypes[0].Descriptor()
}

func (HttpAuthenticationType) Type() protoreflect.EnumType {
	return &file_micro_proto_enumTypes[0]
}

func (x HttpAuthenticationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *HttpAuthenticationType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = HttpAuthenticationType(num)
	return nil
}

// Deprecated: Use HttpAuthenticationType.Descriptor instead.
func (HttpAuthenticationType) EnumDescriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{0}
}

type ParameterType int32

const (
	ParameterType_PARAMETER_TYPE_UNSPECIFIED ParameterType = 0
	ParameterType_PARAMETER_TYPE_STRING      ParameterType = 1
	ParameterType_PARAMETER_TYPE_NUMBER      ParameterType = 2
)

// Enum value maps for ParameterType.
var (
	ParameterType_name = map[int32]string{
		0: "PARAMETER_TYPE_UNSPECIFIED",
		1: "PARAMETER_TYPE_STRING",
		2: "PARAMETER_TYPE_NUMBER",
	}
	ParameterType_value = map[string]int32{
		"PARAMETER_TYPE_UNSPECIFIED": 0,
		"PARAMETER_TYPE_STRING":      1,
		"PARAMETER_TYPE_NUMBER":      2,
	}
)

func (x ParameterType) Enum() *ParameterType {
	p := new(ParameterType)
	*p = x
	return p
}

func (x ParameterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParameterType) Descriptor() protoreflect.EnumDescriptor {
	return file_micro_proto_enumTypes[1].Descriptor()
}

func (ParameterType) Type() protoreflect.EnumType {
	return &file_micro_proto_enumTypes[1]
}

func (x ParameterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ParameterType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ParameterType(num)
	return nil
}

// Deprecated: Use ParameterType.Descriptor instead.
func (ParameterType) EnumDescriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{1}
}

type Database struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name *string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (x *Database) Reset() {
	*x = Database{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Database) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Database) ProtoMessage() {}

func (x *Database) ProtoReflect() protoreflect.Message {
	mi := &file_micro_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Database.ProtoReflect.Descriptor instead.
func (*Database) Descriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{0}
}

func (x *Database) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Http *ServiceHttp `protobuf:"bytes,1,opt,name=http" json:"http,omitempty"`
}

func (x *Service) Reset() {
	*x = Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_micro_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{1}
}

func (x *Service) GetHttp() *ServiceHttp {
	if x != nil {
		return x.Http
	}
	return nil
}

type Method struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Http *MethodHttp `protobuf:"bytes,1,opt,name=http" json:"http,omitempty"`
}

func (x *Method) Reset() {
	*x = Method{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Method) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Method) ProtoMessage() {}

func (x *Method) ProtoReflect() protoreflect.Message {
	mi := &file_micro_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Method.ProtoReflect.Descriptor instead.
func (*Method) Descriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{2}
}

func (x *Method) GetHttp() *MethodHttp {
	if x != nil {
		return x.Http
	}
	return nil
}

type MethodHttp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth   *bool        `protobuf:"varint,1,opt,name=auth" json:"auth,omitempty"`
	Scope  []string     `protobuf:"bytes,2,rep,name=scope" json:"scope,omitempty"`
	Header []*Parameter `protobuf:"bytes,3,rep,name=header" json:"header,omitempty"`
}

func (x *MethodHttp) Reset() {
	*x = MethodHttp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MethodHttp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MethodHttp) ProtoMessage() {}

func (x *MethodHttp) ProtoReflect() protoreflect.Message {
	mi := &file_micro_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MethodHttp.ProtoReflect.Descriptor instead.
func (*MethodHttp) Descriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{3}
}

func (x *MethodHttp) GetAuth() bool {
	if x != nil && x.Auth != nil {
		return *x.Auth
	}
	return false
}

func (x *MethodHttp) GetScope() []string {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *MethodHttp) GetHeader() []*Parameter {
	if x != nil {
		return x.Header
	}
	return nil
}

type ServiceHttp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authentication *ServiceAuthentication `protobuf:"bytes,1,opt,name=authentication" json:"authentication,omitempty"`
	Header         []*Parameter           `protobuf:"bytes,2,rep,name=header" json:"header,omitempty"`
}

func (x *ServiceHttp) Reset() {
	*x = ServiceHttp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceHttp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceHttp) ProtoMessage() {}

func (x *ServiceHttp) ProtoReflect() protoreflect.Message {
	mi := &file_micro_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceHttp.ProtoReflect.Descriptor instead.
func (*ServiceHttp) Descriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceHttp) GetAuthentication() *ServiceAuthentication {
	if x != nil {
		return x.Authentication
	}
	return nil
}

func (x *ServiceHttp) GetHeader() []*Parameter {
	if x != nil {
		return x.Header
	}
	return nil
}

type ServiceAuthentication struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *HttpAuthenticationType `protobuf:"varint,1,opt,name=type,enum=micro.HttpAuthenticationType" json:"type,omitempty"`
}

func (x *ServiceAuthentication) Reset() {
	*x = ServiceAuthentication{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceAuthentication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAuthentication) ProtoMessage() {}

func (x *ServiceAuthentication) ProtoReflect() protoreflect.Message {
	mi := &file_micro_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAuthentication.ProtoReflect.Descriptor instead.
func (*ServiceAuthentication) Descriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{5}
}

func (x *ServiceAuthentication) GetType() HttpAuthenticationType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return HttpAuthenticationType_MICRO_HTTP_AUTHENTICATION_TYPE_UNSPECIFIED
}

type Parameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     *string        `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Type     *ParameterType `protobuf:"varint,2,opt,name=type,enum=micro.ParameterType" json:"type,omitempty"`
	Required *bool          `protobuf:"varint,3,opt,name=required" json:"required,omitempty"`
}

func (x *Parameter) Reset() {
	*x = Parameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_micro_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Parameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Parameter) ProtoMessage() {}

func (x *Parameter) ProtoReflect() protoreflect.Message {
	mi := &file_micro_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Parameter.ProtoReflect.Descriptor instead.
func (*Parameter) Descriptor() ([]byte, []int) {
	return file_micro_proto_rawDescGZIP(), []int{6}
}

func (x *Parameter) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Parameter) GetType() ParameterType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ParameterType_PARAMETER_TYPE_UNSPECIFIED
}

func (x *Parameter) GetRequired() bool {
	if x != nil && x.Required != nil {
		return *x.Required
	}
	return false
}

var file_micro_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FileOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         66041,
		Name:          "micro.micro_app_name",
		Tag:           "bytes,66041,opt,name=micro_app_name",
		Filename:      "micro.proto",
	},
	{
		ExtendedType:  (*descriptor.ServiceOptions)(nil),
		ExtensionType: (*Service)(nil),
		Field:         66041,
		Name:          "micro.service",
		Tag:           "bytes,66041,opt,name=service",
		Filename:      "micro.proto",
	},
	{
		ExtendedType:  (*descriptor.MethodOptions)(nil),
		ExtensionType: (*Method)(nil),
		Field:         66041,
		Name:          "micro.method",
		Tag:           "bytes,66041,opt,name=method",
		Filename:      "micro.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*Database)(nil),
		Field:         66041,
		Name:          "micro.database",
		Tag:           "bytes,66041,opt,name=database",
		Filename:      "micro.proto",
	},
}

// Extension fields to descriptor.FileOptions.
var (
	// optional string micro_app_name = 66041;
	E_MicroAppName = &file_micro_proto_extTypes[0]
)

// Extension fields to descriptor.ServiceOptions.
var (
	// optional micro.Service service = 66041;
	E_Service = &file_micro_proto_extTypes[1]
)

// Extension fields to descriptor.MethodOptions.
var (
	// optional micro.Method method = 66041;
	E_Method = &file_micro_proto_extTypes[2]
)

// Extension fields to descriptor.FieldOptions.
var (
	// optional micro.Database database = 66041;
	E_Database = &file_micro_proto_extTypes[3]
)

var File_micro_proto protoreflect.FileDescriptor

var file_micro_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d,
	0x69, 0x63, 0x72, 0x6f, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x26, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48,
	0x74, 0x74, 0x70, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x22, 0x2f, 0x0a, 0x06, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x25, 0x0a, 0x04, 0x68, 0x74, 0x74, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x48, 0x74, 0x74, 0x70, 0x52, 0x04, 0x68, 0x74, 0x74, 0x70, 0x22, 0x60, 0x0a, 0x0a, 0x4d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x48, 0x74, 0x74, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x14, 0x0a, 0x05,
	0x73, 0x63, 0x6f, 0x70, 0x65, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x73, 0x63, 0x6f,
	0x70, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x03, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x7d, 0x0a, 0x0b,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x48, 0x74, 0x74, 0x70, 0x12, 0x44, 0x0a, 0x0e, 0x61,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x52, 0x0e, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x28, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x4a, 0x0a, 0x15, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x31, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x41,
	0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x65, 0x0a, 0x09, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x28, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75, 0x69, 0x72, 0x65, 0x64, 0x2a, 0x73,
	0x0a, 0x16, 0x48, 0x74, 0x74, 0x70, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x2a, 0x4d, 0x49, 0x43, 0x52,
	0x4f, 0x5f, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45,
	0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x29, 0x0a, 0x25, 0x4d, 0x49, 0x43, 0x52,
	0x4f, 0x5f, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x45, 0x4e, 0x54, 0x49, 0x43,
	0x41, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45, 0x41, 0x52, 0x45,
	0x52, 0x10, 0x01, 0x2a, 0x65, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45,
	0x52, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12,
	0x19, 0x0a, 0x15, 0x50, 0x41, 0x52, 0x41, 0x4d, 0x45, 0x54, 0x45, 0x52, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x4e, 0x55, 0x4d, 0x42, 0x45, 0x52, 0x10, 0x02, 0x3a, 0x44, 0x0a, 0x0e, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x5f, 0x61, 0x70, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46,
	0x69, 0x6c, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf9, 0x83, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x41, 0x70, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x3a, 0x4b, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf9, 0x83, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x3a, 0x47, 0x0a,
	0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf9, 0x83, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0d, 0x2e, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x06,
	0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x3a, 0x4c, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61,
	0x73, 0x65, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x18, 0xf9, 0x83, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61,
	0x62, 0x61, 0x73, 0x65, 0x42, 0x41, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x72, 0x73, 0x66, 0x72, 0x65, 0x69, 0x74, 0x61, 0x73, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x2d, 0x6d, 0x69,
	0x63, 0x72, 0x6f, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x6d, 0x69, 0x63, 0x72,
	0x6f, 0x3b, 0x6d, 0x69, 0x63, 0x72, 0x6f,
}

var (
	file_micro_proto_rawDescOnce sync.Once
	file_micro_proto_rawDescData = file_micro_proto_rawDesc
)

func file_micro_proto_rawDescGZIP() []byte {
	file_micro_proto_rawDescOnce.Do(func() {
		file_micro_proto_rawDescData = protoimpl.X.CompressGZIP(file_micro_proto_rawDescData)
	})
	return file_micro_proto_rawDescData
}

var file_micro_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_micro_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_micro_proto_goTypes = []interface{}{
	(HttpAuthenticationType)(0),       // 0: micro.HttpAuthenticationType
	(ParameterType)(0),                // 1: micro.ParameterType
	(*Database)(nil),                  // 2: micro.Database
	(*Service)(nil),                   // 3: micro.Service
	(*Method)(nil),                    // 4: micro.Method
	(*MethodHttp)(nil),                // 5: micro.MethodHttp
	(*ServiceHttp)(nil),               // 6: micro.ServiceHttp
	(*ServiceAuthentication)(nil),     // 7: micro.ServiceAuthentication
	(*Parameter)(nil),                 // 8: micro.Parameter
	(*descriptor.FileOptions)(nil),    // 9: google.protobuf.FileOptions
	(*descriptor.ServiceOptions)(nil), // 10: google.protobuf.ServiceOptions
	(*descriptor.MethodOptions)(nil),  // 11: google.protobuf.MethodOptions
	(*descriptor.FieldOptions)(nil),   // 12: google.protobuf.FieldOptions
}
var file_micro_proto_depIdxs = []int32{
	6,  // 0: micro.Service.http:type_name -> micro.ServiceHttp
	5,  // 1: micro.Method.http:type_name -> micro.MethodHttp
	8,  // 2: micro.MethodHttp.header:type_name -> micro.Parameter
	7,  // 3: micro.ServiceHttp.authentication:type_name -> micro.ServiceAuthentication
	8,  // 4: micro.ServiceHttp.header:type_name -> micro.Parameter
	0,  // 5: micro.ServiceAuthentication.type:type_name -> micro.HttpAuthenticationType
	1,  // 6: micro.Parameter.type:type_name -> micro.ParameterType
	9,  // 7: micro.micro_app_name:extendee -> google.protobuf.FileOptions
	10, // 8: micro.service:extendee -> google.protobuf.ServiceOptions
	11, // 9: micro.method:extendee -> google.protobuf.MethodOptions
	12, // 10: micro.database:extendee -> google.protobuf.FieldOptions
	3,  // 11: micro.service:type_name -> micro.Service
	4,  // 12: micro.method:type_name -> micro.Method
	2,  // 13: micro.database:type_name -> micro.Database
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	11, // [11:14] is the sub-list for extension type_name
	7,  // [7:11] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_micro_proto_init() }
func file_micro_proto_init() {
	if File_micro_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_micro_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Database); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Method); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MethodHttp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceHttp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceAuthentication); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_micro_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Parameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_micro_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_micro_proto_goTypes,
		DependencyIndexes: file_micro_proto_depIdxs,
		EnumInfos:         file_micro_proto_enumTypes,
		MessageInfos:      file_micro_proto_msgTypes,
		ExtensionInfos:    file_micro_proto_extTypes,
	}.Build()
	File_micro_proto = out.File
	file_micro_proto_rawDesc = nil
	file_micro_proto_goTypes = nil
	file_micro_proto_depIdxs = nil
}
